# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-19 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipamento', models.CharField(max_length=200)),
                ('marca_equipamento', models.CharField(max_length=200)),
                ('modelo_equipamento', models.CharField(max_length=200)),
                ('nome_equipamento', models.CharField(max_length=200)),
            ],
        ),
    ]
