# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-28 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_equipamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='foto_equipamento',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
